######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 7 09:11:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11

# Input
SOURCES += main.cpp
